version: "3.9"

services:
  dev-db:
    image: "postgres:latest"
    container_name: "fortune-pg"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=postgres
    volumes:
      - ../../.db/dev-postgres/data:/var/lib/postgresql/data

networks:
  default:
    name: devnet
